//Use the same namespace than the TYPE for the Valves state

NAMESPACE FluidHandlingClass   

    CLASS TankBase
        VAR
            
        END_VAR
        
        METHOD PUBLIC Fill 
            ;
        END_METHOD

        METHOD PUBLIC Flush
            ;        
        END_METHOD

        METHOD PUBLIC Close
            ;
        END_METHOD

        METHOD PUBLIC Emptying
            ;
        END_METHOD

    END_CLASS
    
END_NAMESPACE